### ISSUE TITLE
Anzeige Publ. EN

### ISSUE THREAD

**Issue by STruckenbrodt** [fieldmapp/fieldmapp.github.io#5]
Die Struktur für Publikationen (Sprache DE) wurde übernommen, um die Publikationsseite auf Englisch vorzubreiten. Dabei wurde der originale Aufbau der Files beibhalten und nur die angezeigten Texte durch englischsprachige ersetzt. Dennoch kann der hinzugefügte Inhalt nicht angezeigt werden. @BMI24 : Hast du eine Idee woran das liegt?

**Comment by BMI24** [comment]
Wenn du auf der Hauptseite von unserem Github-Repo bist, siehst du oben bei dem neusten Commit/ der neuesten Änderung den Verarbeitungsstatus davon (rotes Kreutz oder grüner Haken). Wenn du den anklickst kommst du auf eine Seite wie [die hier](https://github.com/fieldmapp/fieldmapp.github.io/runs/4944823615?check_suite_focus=true), da kannst du ungefähr sehen um welche Datei es geht und wo der Fehler liegt (leider nur sehr ungefähr). `Error: Error building site: "/home/runner/work/fieldmapp.github.io/fieldmapp.github.io/content/en/publications/core/_index.md:15:1": failed to unmarshal YAML: yaml: line 14: could not find expected ':'` zeigt dir den Pfad zur Datei. In dem Fall waren das jetzt ein kleiner Synatxfehler, den ich in  https://github.com/fieldmapp/fieldmapp.github.io/commit/f8786514d56feba83ea0d3ef85677fd9ed99f8f0 korregiert hab. Dann gab es noch einen, den ich in https://github.com/fieldmapp/fieldmapp.github.io/commit/36d01fedb4e245b680d3df3d1ea656b741dea62f behoben hab, jetzt soweit alles.

**Comment by STruckenbrodt** [comment]
Danke für die Infos und die Korrekturen. Die Fehlermeldungen hatte ich mir gestern bereits angesehen. Hab mit deren Hilfe den Fehler nur leider nicht gefunden. Ich hoffe, dass ich schnell dazu lerne und dich dann nicht mehr wegen solcher Bagatellen behelligen muss.
